org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.59-beta

mod_id=swingthrough
mod_name=Swing Through
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=astra.swingthrough
